/**
 * Automatically generated types for motia
 * Do NOT edit this file manually
 */
import 'motia'
import '@motiadev/core'

declare module 'motia' {
  interface FlowContextStreams {
    openai: ObjectStream<{ message: string }>
  }

  interface EmitData {
    topic: 'openai-prompt'
    data: { message: string }
  }

  type Emitter = (event: EmitData) => Promise<void>
}
