/**
 * Automatically generated types for motia
 * Do NOT edit this file manually
 */
import 'motia'

declare module 'motia' {
  interface FlowContextStreams {
    openai: ObjectStream<{ message: string }>
  }

  type EmitData = { topic: 'openai-prompt'; data: { message: string } }
}
