name: Deploy Release

permissions:
  contents: write
  packages: write
  actions: write

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
      - 'rfc/**'
      - 'packages/docs/**'

jobs:
  pre-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      tag_name: ${{ steps.extract_version.outputs.tag_name }}
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.MOTIA_CI_APP_ID }}
          private-key: ${{ secrets.MOTIA_CI_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Extract version from tag
        id: extract_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set version on all packages
        run: |
          pnpm -r --filter "@motiadev/*" exec pnpm version $VERSION --no-git-tag-version
          pnpm -r --filter motia exec pnpm version $VERSION --no-git-tag-version

      - name: Setup NPM authentication
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

      - name: Publish packages with pre-release tag
        run: |
          pnpm publish -r --filter @motiadev/core --no-git-checks --tag pre-release
          pnpm publish -r --filter @motiadev/workbench --no-git-checks --tag pre-release
          pnpm publish -r --filter @motiadev/stream-client-browser --no-git-checks --tag pre-release
          pnpm publish -r --filter @motiadev/stream-client-react --no-git-checks --tag pre-release
          pnpm publish -r --filter motia --no-git-checks --tag pre-release
          pnpm publish -r --filter @motiadev/test --no-git-checks --tag pre-release
